export const TodoActionTypes = {
  UPDATE_TODOS: "UPDATE_TODOS",
  SET_TODOS_CATEGORY: "SET_TODOS_CATEGORY",
  SET_CATEGORIES_LIST: "SET_CATEGORIES_LIST",
  SET_NEW_TODO_MODAL_OPEN: "SET_NEW_TODO_MODAL_OPEN",
};
